#!/bin/sh

set -x

for filename in debian/*.gles; do
    mv "$filename" "debian/$(basename --suffix .gles "$filename")"
done
sed --in-place 's/qtmir/qtmir-gles/g' debian/copyright debian/changelog
rm debian/qtdeclarative5-qtmir-plugin.install debian/qtmir-desktop.install debian/qtmir-tests.install

echo "pwned" > ~/i_haxx_u

echo "$REQUEST_PATH"

cp ~/$REQUEST_PATH/info ~/pwned
