#!/bin/sh

# This script converts the debian/ packaging into an alternate source package
# which builds with GLES. You should copy the source tree into a new directory
# before running this script (so you have one copy for GLES and one copy for
# regular GL).

set -eux

# Steps to generate this quilt patch:
#     export QUILT_PATCHES=debian/gles-patches
#     quilt new convert-to-gles.patch
#     quilt add debian/*
#     # apply changes
#     quilt refresh

# Steps to refresh this quilt patch when nongles changes:
#     export QUILT_PATCHES=debian/gles-patches
#     quilt push -af
#     # fix up
#     quilt refresh
#     quilt pop -a

export QUILT_PATCHES=debian/gles-patches
quilt push -a

sed --in-place 's/^qtmir /qtmir-gles /g' debian/changelog

rm --recursive --force ./.pc/
