#!/bin/sh

# This script converts the debian/ packaging into an alternate source package
# which builds with GLES. You should copy the source tree into a new directory
# before running this script (so you have one copy for GLES and one copy for
# regular GL).

set -eu

# Steps to start a new quilt patch:
#     quilt new convert-to-gles.patch
#     quilt add debian/*
#     # apply changes

# Steps to refresh this quilt patch when nongles changes:
#     quilt push -af
#     # fix up

# When finished, save quilt patch with:
#     quilt refresh
#     quilt pop -a

export QUILT_PATCHES=debian/gles-patches
quilt push -a

sed --in-place 's/^qtmir /qtmir-gles /g' debian/changelog

rm --recursive --force ./.pc/
